// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CheckData,
  CheckResponses,
  CreateData,
  CreateResponses,
  DestroyData,
  DestroyErrors,
  DestroyResponses,
  GetAllData,
  GetAllResponses,
  GetByIdData,
  GetByIdErrors,
  GetByIdResponses,
  UpdateData,
  UpdateErrors,
  UpdateResponses,
} from "./types.gen";
import {
  z_check_data,
  z_create_data,
  z_destroy_data,
  z_get_all_data,
  z_get_by_id_data,
  z_update_data,
} from "./zod.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const check = <ThrowOnError extends boolean = false>(
  options?: Options<CheckData, ThrowOnError>,
) =>
  (options?.client ?? client).get<CheckResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z_check_data.parseAsync(data),
    url: "/api/v1/health",
    ...options,
  });

export const getAll = <ThrowOnError extends boolean = false>(
  options?: Options<GetAllData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetAllResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z_get_all_data.parseAsync(data),
    url: "/api/v1/todos",
    ...options,
  });

export const create = <ThrowOnError extends boolean = false>(
  options: Options<CreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<CreateResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await z_create_data.parseAsync(data),
    url: "/api/v1/todos",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const destroy = <ThrowOnError extends boolean = false>(
  options: Options<DestroyData, ThrowOnError>,
) =>
  (options.client ?? client).delete<
    DestroyResponses,
    DestroyErrors,
    ThrowOnError
  >({
    requestValidator: async (data) => await z_destroy_data.parseAsync(data),
    url: "/api/v1/todos/{id}",
    ...options,
  });

export const getById = <ThrowOnError extends boolean = false>(
  options: Options<GetByIdData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetByIdResponses, GetByIdErrors, ThrowOnError>(
    {
      requestValidator: async (data) => await z_get_by_id_data.parseAsync(data),
      url: "/api/v1/todos/{id}",
      ...options,
    },
  );

export const update = <ThrowOnError extends boolean = false>(
  options: Options<UpdateData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateResponses, UpdateErrors, ThrowOnError>({
    requestValidator: async (data) => await z_update_data.parseAsync(data),
    url: "/api/v1/todos/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
