// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  CheckData,
  CheckResponses,
  CreateData,
  CreateResponses,
  DestroyData,
  DestroyErrors,
  DestroyResponses,
  GetAllData,
  GetAllResponses,
  GetByIdData,
  GetByIdErrors,
  GetByIdResponses,
  UpdateData,
  UpdateErrors,
  UpdateResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Health {
  public static check<ThrowOnError extends boolean = false>(
    options?: Options<CheckData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      CheckResponses,
      unknown,
      ThrowOnError
    >({ url: "/health", ...options });
  }
}

export class Todo {
  public static getAll<ThrowOnError extends boolean = false>(
    options?: Options<GetAllData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetAllResponses,
      unknown,
      ThrowOnError
    >({ url: "/todos", ...options });
  }

  public static create<ThrowOnError extends boolean = false>(
    options: Options<CreateData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      CreateResponses,
      unknown,
      ThrowOnError
    >({
      url: "/todos",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static destroy<ThrowOnError extends boolean = false>(
    options: Options<DestroyData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      DestroyResponses,
      DestroyErrors,
      ThrowOnError
    >({ url: "/todos/{id}", ...options });
  }

  public static getById<ThrowOnError extends boolean = false>(
    options: Options<GetByIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      GetByIdResponses,
      GetByIdErrors,
      ThrowOnError
    >({ url: "/todos/{id}", ...options });
  }

  public static update<ThrowOnError extends boolean = false>(
    options: Options<UpdateData, ThrowOnError>,
  ) {
    return (options.client ?? client).put<
      UpdateResponses,
      UpdateErrors,
      ThrowOnError
    >({
      url: "/todos/{id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
