// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:7878" | (string & {});
};

export type CreateTodo = {
  title: string;
};

export type HealthResponse = {
  status: string;
  version?: string | null;
};

export type Todo = {
  completed: boolean;
  id: number;
  title: string;
};

export type UpdateTodo = {
  completed?: boolean | null;
  title?: string | null;
};

export type CheckData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type CheckResponses = {
  /**
   * Service is healthy
   */
  200: HealthResponse;
};

export type CheckResponse = CheckResponses[keyof CheckResponses];

export type GetAllData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/todos";
};

export type GetAllResponses = {
  /**
   * List all todos
   */
  200: Array<Todo>;
};

export type GetAllResponse = GetAllResponses[keyof GetAllResponses];

export type CreateData = {
  body: CreateTodo;
  path?: never;
  query?: never;
  url: "/todos";
};

export type CreateResponses = {
  /**
   * Create a new todo
   */
  201: Todo;
};

export type CreateResponse = CreateResponses[keyof CreateResponses];

export type DestroyData = {
  body?: never;
  path: {
    /**
     * Todo ID
     */
    id: number;
  };
  query?: never;
  url: "/todos/{id}";
};

export type DestroyErrors = {
  /**
   * Todo not found
   */
  404: unknown;
};

export type DestroyResponses = {
  /**
   * Delete a todo
   */
  204: void;
};

export type DestroyResponse = DestroyResponses[keyof DestroyResponses];

export type GetByIdData = {
  body?: never;
  path: {
    /**
     * Todo ID
     */
    id: number;
  };
  query?: never;
  url: "/todos/{id}";
};

export type GetByIdErrors = {
  /**
   * Todo not found
   */
  404: unknown;
};

export type GetByIdResponses = {
  /**
   * Get a todo by id
   */
  200: Todo;
};

export type GetByIdResponse = GetByIdResponses[keyof GetByIdResponses];

export type UpdateData = {
  body: UpdateTodo;
  path: {
    /**
     * Todo ID
     */
    id: number;
  };
  query?: never;
  url: "/todos/{id}";
};

export type UpdateErrors = {
  /**
   * Todo not found
   */
  404: unknown;
};

export type UpdateResponses = {
  /**
   * Update a todo
   */
  200: Todo;
};

export type UpdateResponse = UpdateResponses[keyof UpdateResponses];
