// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

export const z_create_todo = z.object({
  title: z.string().min(5).max(255),
});

export const z_health_response = z.object({
  status: z.string(),
  version: z.optional(z.union([z.string(), z.null()])),
});

export const z_todo = z.object({
  completed: z.boolean(),
  id: z.coerce
    .bigint()
    .min(BigInt("-9223372036854775808"), {
      error: "Invalid value: Expected int64 to be >= -9223372036854775808",
    })
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    }),
  title: z.string(),
});

export const z_update_todo = z.object({
  completed: z.optional(z.union([z.boolean(), z.null()])),
  title: z.optional(z.union([z.string(), z.null()])),
});
